### ISSUE TITLE
Linking to static libraries does not work on Windows

### ISSUE THREAD

**Issue by mkilgore** [QB64-Phoenix-Edition/QB64pe#112]
As part of resolving static libraries, we have to insert declarations for the functions being used via the static library into our code. Doing this requires determining what kind of symbol we're calling (C or C++), which we do via utilizing `nm` which can give us this information.

Functionally all the code around it is correct, but the shell call to nm.exe does not include the necessary `cmd /c`, which leads to the redirection failing to work (and leaving us unable to read the file). Thus we need to change the two lines that look like this:

```basic
SHELL _HIDE "internal\c\c_compiler\bin\nm.exe "...
```

To this:

```basic
SHELL _HIDE "cmd /c internal\c\c_compiler\bin\nm.exe "...
```

There are two that need to be addressed, the Linux and OSX versions should already work as expected.

As part of this card we should add some new tests for static libraries (for all three platforms) and also potentially consider combining the Linux and Windows handling of `nm` output, since it appeasr to be identical except for the actual shell call.

**Comment by a740g** [comment]
@mkilgore Thank you for the workaround. It worked for me and for another user. See [here](https://qb64phoenix.com/forum/showthread.php?tid=557&pid=3635#pid3635).

I actually changed two lines. I also put `cmd.exe` so that this does try to execute a .cmd or .bat or .com etc.
```VB
12550 Shell _Hide "cmd.exe /c internal\c\c_compiler\bin\nm.exe " + Chr$(34) + ResolveStaticFunction_File(x) + Chr$(34) + " --demangle -g >internal\temp\nm_output.txt"

12604 Shell _Hide "cmd.exe /c internal\c\c_compiler\bin\nm.exe " + Chr$(34) + ResolveStaticFunction_File(x) + Chr$(34) + " -D --demangle -g >.\internal\temp\nm_output_dynamic.txt"
```

Maybe we can make this fix a part of the next release?

**Comment by mkilgore** [comment]
Yes, sorry it's been so long, the only thing this was waiting on was writing a few test cases to verify the behavior, I'll try to make a point of prioritizing this since it is really pretty simple.
