### ISSUE TITLE
Add an ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by mkilgore** [QB64-Phoenix-Edition/QB64pe#17]
The previous repository had one, potentially we can just reuse it. It has good information on what to provide us about the bug.

**Comment by grymmjack** [comment]
Is it just something in .GitHub/ directory that gets included when a new issue is created? If so where is the old one?

**Comment by mkilgore** [comment]
@grymmjack I don't know too much about it, but it looks like it's a directory inside of `.github/`. You can see the old ones that were in the QB64Team repo here: https://github.com/QB64Team/qb64/tree/development/.github/ISSUE_TEMPLATE
