### ISSUE TITLE
_DEVICES fails to compile in $CONSOLE:ONLY

### ISSUE THREAD

**Issue by SpriggsySpriggs** [QB64-Phoenix-Edition/QB64pe#178]
I'm not sure if this is intentional or not but using _DEVICES causes the program to fail compilation. When I commented out $CONSOLE:ONLY, the program compiled just fine. I don't see on the help page anything about not being compatible in console programs.

**Comment by mkilgore** [comment]
Sounds like a bug in the build logic, I can investigate it later when I have time. As a complete guess though you might try going into the `Compiler Settings` menu and adding `-lwinmm` as a linker flag, that might fix it. That library doesn't get linked to when `$CONSOLE:ONLY` is used but it looks like the Gamepad stuff needs it.

**Comment by SpriggsySpriggs** [comment]
Yep, linking that library did fix the issue

**Comment by mkilgore** [comment]
Well that was easy :D I'll try to get a fix out for that soon, good catch.
