### ISSUE TITLE
Optimize `GenerateWaveform`

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#186]
`GenerateWaveform` in `audio.cpp` generates stereo waveform which is used by `SOUND` and `PLAY`. `SOUND` and `PLAY` have no stereo capabilities and hence generating stereo waveform is a waste of memory and processing resources.

`GenerateWaveform` should be rewritten to generate mono waveform instead.

**Comment by barcoboy** [comment]
As I mentioned in #217, the sound generated by PLAY is a triangle waveform, where QB45 generates a near square waveform.
