### ISSUE TITLE
Amiga BASIC like `WAVE` and `SOUND` improvements

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#187]
Amiga Basic programs can produce high quality sound for games, music applications, or user alerts. The SOUND statement emits tone of specified frequency, duration, and volume. As an option, the tone can also have one of four user-defined "voices." The WAVE statement lets you assign your own complex waveforms to each of the voices. SOUND and WAVE can provide your programs with rich variety of musical sounds, from the complexity of string quartet to the simplicity of whistled tune.

These features can be implemented as:
`SOUND frequency, duration [, [volume ][, voice ]]`
`SOUND _WAIT` (or an extra parameter for `SOUND` above)
`SOUND _RESUME` (or an extra parameter for `SOUND` above)
`_WAVE voice, wave-definition`

See [Amiga_BASIC_1985_Commodore.pdf](https://github.com/QB64-Phoenix-Edition/QB64pe/files/9612137/Amiga_BASIC_1985_Commodore.pdf) for more information.

**Comment by grymmjack** [comment]
`_WAVE` <3 would be amazing.
