### ISSUE TITLE
Platform agnostic `common dialogs` support

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#189]
We should provide a way to support `common dialogs` (like MessageBox, InputBox, PasswordBox, ColorPicker, OpenFileDialog, SaveFileDialog, SelectFolderDialog, Tray-popup, Notification Beep) in a platform agnostic manner.

`libqb.cpp` already has rudimentary support for `MessageBox` & `Alert`. However, these can be significantly improved and extended.

From my observations most folks resort to calling native OS libraries for these functionalities which ties the code to a particular platform. Also, supporting common dialogs for multiple platforms on the BASIC side is rather complicated and complex.

My recommendation is to use a tried, tested and compact library like [tiny file dialogs](https://sourceforge.net/projects/tinyfiledialogs/).
Using this we can then have VB-style dialog functions like `_GetOpenFilename`, `_MsgBox`, `_InputBox`, etc...

**Comment by SpriggsySpriggs** [comment]
I like this idea. I don't typically do cross-platform code so when I do dialogs they always are platform specific. However, I could cut down on BAS code by having an internal dialog function like this.
