### ISSUE TITLE
Issues with the PLAY statement

### ISSUE THREAD

**Issue by barcoboy** [QB64-Phoenix-Edition/QB64pe#217]
According to the QB64 help text, the PLAY statement "N" parameter can be used to play a note "between 0 to 84 in the 7 octaves, where 0 is a rest).  However, the 0 value to N does not play a rest, but plays a low C note instead.   The following code should play 4 beeps with rests in between, but instead plays a high G, then a low C, high G, low C, etc.

PLAY "T120O4L4GN0GN0GN0GN0"

Actually all "N" notes should be shifted up by one as compared to QuickBASIC 4.5.  Right now, N0 in QB64 is N1 in QB4,5, which is a low C.  An octave higher N12 in QB64 is N13 in QB4.5, and so on.

Also the sound of the notes in QB4.5 is a louder square waveform as compared to the softer triangle waveform of QB64... wondering if that could be changed as well?

**Comment by a740g** [comment]
> Also the sound of the notes in QB4.5 is a louder square waveform as compared to the softer triangle waveform of QB64... wondering if that could be changed as well?

I actually got square waveform working in my [miniaudio-fixes ](https://github.com/a740g/QB64pe/tree/miniaudio-fixes) branch but removed it. It was much simpler and shorter than the current implementation and seemed to work quite well except for cases where `PLAY` played multiple notes together (see example 5 in https://qb64phoenix.com/qb64wiki/index.php/PLAY). Well, mixing two square waves just sounds awful (or probaly we can do better). I'll investigate this in detail later. But for now, we'll stick to the current implementation.

The other fixes here are done and ready for review. Thanks to @mkilgore for figuring out the octave fix.
