### ISSUE TITLE
Update InForm to work with QB64pe

### ISSUE THREAD

**Issue by GeorgeMcGinn** [QB64-Phoenix-Edition/QB64pe#221]
Currently InForm will not work properly with QB64pe. That is, if you try to install InForm intoQB64pe, it looks for qb64 executables for both installation and when exiting, it looks for the qb64 IDE.

Changes need to be made to UiEditor.bas in order to either determine which version of QB64 is installed, or create a separate InForm for QB64pe.

**Comment by a740g** [comment]
@GeorgeMcGinn I am closing this as you have already addressed this issue in https://github.com/GeorgeMcGinn/InForm/blob/master/InForm/UiEditor.bas#L209
