### ISSUE TITLE
What's the difference between qb64pe and qb64?

### ISSUE THREAD

**Issue by fpemud** [QB64-Phoenix-Edition/QB64pe#229]
After reading all issues and some search, I still have totally no idea about what the difference is between qb64pe and the [version1](https://github.com/QB64Official/qb64), [version2](https://github.com/QB64Team/qb64) of qb64.
It seems all three projects are being actively developed.
Shouldn't this information be in FAQ?

**Comment by mkilgore** [comment]
QB64Team/qb64 is no longer actively maintained, both QB64Official/qb64 and QB64-Phoenix-Edition/QB64pe are forks of that code maintained by different people. The differences between us and the last QB64Team/qb64 version are just everything listed in our release notes. For changes made to QB64Official/qb64 I would refer to their release notes.

> Shouldn't this information be in FAQ?

Yeah I agree it could be made clearer somewhere, I'll see about doing that. We mention the situation a bit on the [v3.0.0](https://github.com/QB64-Phoenix-Edition/QB64pe/releases/tag/v3.0.0) release, in that we're compatible with all code for QB64 v2.0.2 (which is the last release from the QB64Team/qb64 repo), but if you don't already know what's up a bit then that probably doesn't make a whole lot of sense on its own.
