### ISSUE TITLE
The layout of expressions after `UBOUND()` and `LBOUND()` is wrong

### ISSUE THREAD

**Issue by mkilgore** [QB64-Phoenix-Edition/QB64pe#244]
See the forum post [here](https://qb64phoenix.com/forum/showthread.php?tid=1109)

Basically, if you have syntax formatting on and you type this:

```vb
REDIM c$(1000)
idx = UBOUND(c$) - _HEIGHT - 125
```

The second line gets incorrectly transformed into this:

```vb
REDIM c$(1000)
idx = UBOUND(c$) - _HEIGHT (
```

It seems like `UBOUND()` and `LBOUND()` handling is the culprit, putting anything after the `-` results is basically the same kind of incorrect transformation.

This is another card that would benefit from #215, as it would allow us to add tests around these cases.

**Comment by SteveMcNeill** [comment]
This doesn't just affect _HEIGHT.  It affects any automatically handled function with a single optional param after lbound/ubound.  You can also rule out the REDIM statement and see the glitch with something as simple as:

print lBOUND(c) - _pixelsize  - 125
