### ISSUE TITLE
ON TIMER() not firing on 1st interval

### ISSUE THREAD

**Issue by grymmjack** [QB64-Phoenix-Edition/QB64pe#273]
It seems that `ON TIMER()` is not firing on the 1st interval, if it is the first timer set with `_FREETIMER`
I am using `QB64-PE Compiler V3.4.1`

### What I expect to happen:
`TIMER_A_TICKS%` gets incremented every 5 seconds.
`TIMER_B_TICKS%` gets incremented every second.

### What is happening:
`TIMER_A_TICKS%` gets incremented on the 10th second, then every 5 seconds.
`TIMER_B_TICKS%` gets incremented every second.

```basic
DIM SHARED TIMER_A AS INTEGER
DIM SHARED TIMER_A_TICKS AS INTEGER
DIM SHARED TIMER_B AS INTEGER
DIM SHARED TIMER_B_TICKS AS INTEGER

TIMER_A% = _FREETIMER
TIMER_B% = _FREETIMER

TIMER_A_TICKS% = 1
TIMER_B_TICKS% = 1

ON TIMER(TIMER_A%, 5) timer_a_update
ON TIMER(TIMER_B%, 1) timer_b_update
TIMER(TIMER_A%) ON
TIMER(TIMER_B%) ON

DO:
    _LIMIT 30
    LOCATE 1, 1 : PRINT _TRIM$(STR$(TIMER_A_TICKS%));
    LOCATE 3, 1 : PRINT _TRIM$(STR$(TIMER_B_TICKS%));
    _DISPLAY
LOOP UNTIL _KEYHIT = 27
SYSTEM

SUB timer_a_update
    TIMER_A_TICKS% = TIMER_A_TICKS% + 1
END SUB

SUB timer_b_update
    TIMER_B_TICKS% = TIMER_B_TICKS% + 1
END Sub
```

https://user-images.githubusercontent.com/412263/206874388-593ccc93-9030-46d6-981a-01e9c60ed6c8.mp4

Thanks

**Comment by gs-rickchristy** [comment]
Here is an old post that Vince found on the old forum that seems related:
https://qb64forum.alephc.xyz/index.php?topic=3835.msg131830

**Comment by grymmjack** [comment]
Thank you @mkilgore for this fix!
