### ISSUE TITLE
Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by byroniac** [QB64-Phoenix-Edition/QB64pe#311]
In qb64pe_win-x86-3.6.0.7z my Windows 11 Microsoft Defender detected (hopefully a false positive): Trojan:Script/Wacatac.H!ml

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Script/Wacatac.H!ml

**Comment by mkilgore** [comment]
Unfortunately we've had problems with false positives before :-/ I'm confident in saying there should be no issues here. I did however go ahead and scan the unzipped x86 archive with Microsoft Defender and it came back with nothing:

![image](https://user-images.githubusercontent.com/3310024/220250108-8ccff1f1-5e06-4d80-b495-bb83fc6e8f65.png)

I scanned the zipped x86 archive as well, same result:

![image](https://user-images.githubusercontent.com/3310024/220250636-8990be18-0c45-49e4-9349-850257be441f.png)

Those artifacts are built on GitHub and pushed directly to the release, you can see the log of the build that created them [here](https://github.com/QB64-Phoenix-Edition/QB64pe/actions/runs/4218312415).

My general understanding is that sometimes antivirus software just doesn't like compilers. The C++ compiler we package with QB64-PE for Windows comes from [here](https://github.com/niXman/mingw-builds-binaries/releases/tag/12.2.0-rt_v10-rev2), and stuff in there seems to sometimes cause false positives.

**Comment by byroniac** [comment]
Thank you for looking into it. I figured it was probably a fake positive, and I don't want to be the kind of person who just complains about everything. But I did want to bring it up just to be cautious as I had no real idea how to verify one way or the other.
