### ISSUE TITLE
Add Unicode option to `_CLIPBOARD$`

### ISSUE THREAD

**Issue by RhoSigma-QB64** [QB64-Phoenix-Edition/QB64pe#323]
Add an optional parameter to `_CLIPBOARD$` (sub and function) to determine the textformat to use for clipboard operations CF_TEXT/CF_UNICODETEXT.

eg.
```
a$ = _CLIPBOARD$ 'default, use CF_TEXT (current behavior), returning ansi text
a$ = _CLIPBOARD$(UNICODE) 'use CF_UNICODETEXT, returning UTF-16 text
a$ = _CLIPBOARD$(ANSI) 'same as default
```

Related discussion: https://qb64phoenix.com/forum/showthread.php?tid=1572

**Comment by mkilgore** [comment]
> In general that could work, but would pass the buck to us. What happens if there's a unicode on the clipboard which is not available in the currently set IDE codepage? We would need to handle that in any way to avoid further complaints.

We wouldn't be doing any conversion, we would just leave the UTF-8 characters in the string as-is. That's already what happens on Linux (and very likely Mac OS) since they use UTF-8 for everything, so it's really not new behavior. In the Wiki we can just clarify that it's UTF-8 text that is given back (which is valid ASCII as long as no Unicode characters are present).

**Comment by mkilgore** [comment]
> I made some tests and see we can not even use extended ASCII chars in variable/function/type names, but we can use it in literal strings and comments. So what would happen, if e.g. Petr wants to copy'n'paste some of his czech worded code?

Yeah it's a good point, that's quite annoying :-/ I'll have to think about it for a bit.

If we do add separate ansi/unicode options for `_CLIPBOARD$()` then we'll have to consider how it all works cross-platform. Likely, the default will be different depending on the platform (Windows defaults to ANSI, Linux and Mac OS default to Unicode). For ANSI support for Linux and Mac OS we'll also need to consider if we're going to implement actual conversion of the Unicode characters (if a corresponding character exists), or maybe just strip them out.

Beyond that I think it's worth having the `_CLIPBOARD$(UNICODE)` option return UTF-8 on all platforms to make it easier to work with. Linux and Mac OS already return that, on Windows it's a simple conversion we could do when copying the data into the string (Windows already has functions to do it).

**Comment by RhoSigma-QB64** [comment]
> Beyond that I think it's worth having the _CLIPBOARD$(UNICODE) option return UTF-8 on all platforms to make it easier to work with. Linux and Mac OS already return that, on Windows it's a simple conversion we could do when copying the data into the string (Windows already has functions to do it).

No objections, my only concern was to generally change the behavior to unicode/UTF-8, we should definitly keep the current (ANSI) function for the IDE and other existing programs and make unicode optional. How the new unicode stuff is finally handled can still be determined when finally working on the implementation.

**Comment by RhoSigma-QB64** [comment]
Obviously too many uncertainties here, hence closed as "Not planned".
