### ISSUE TITLE
v3.7.0 compile error

### ISSUE THREAD

**Issue by loopy750** [QB64-Phoenix-Edition/QB64pe#340]
I have yet to thoroughly investigate, but updating to 3.7.0 from previous (3.6.0, 3.5.0, etc.) is causing compile errors right off the bat. Attached is the log, which is slightly different each time I try to compile.

Possible font issue?

OS: Windows 11

[compilelog.txt](https://github.com/QB64-Phoenix-Edition/QB64pe/files/11404118/compilelog.txt)

**Comment by mkilgore** [comment]
The issue is that `falcon.h` is making using of internal details of QB64-PE which were likely to change. In v3.7.0 we made changes to those internals to implement new features and improve performance, and it broke `falcon.h`.

The good news is that the functionality in `falcon.h` was implemented into QB64-PE itself in v3.7.0, you should look at using the new `_U*` commands (See [`_UPrintString`](https://qb64phoenix.com/qb64wiki/index.php/UPRINTSTRING)) to replace its usage.

**Comment by loopy750** [comment]
OK thanks, it's making a little more sense. The problem is, I'm kinda stuck, as I didn't write the program InForm v1.3, so it might take a bit of working out.

**Comment by loopy750** [comment]
So I've created an "empty" InForm program, then edited InForm.bi and replaced `Declare Library "falcon"` with `Declare Library ""`.

This is the log, as you can see, mostly `uheight` and `uspacing` errors.

[compilelog.txt](https://github.com/QB64-Phoenix-Edition/QB64pe/files/11411878/compilelog.txt)

**Comment by mkilgore** [comment]
We're working on one extra command (see #341), but after that it should be trivial to write a drop-in set of functions to replace `falcon.h`, we'll likely provide that for you and others to use. You'll just remove the `Declare Library` section entirely and then add new QB64 functions that have the same names as the `falcon.h` functions.

**Comment by loopy750** [comment]
Ok that sounds good, thanks. For now I'll have to use 3.6.0 but will definitely try the next version when released.

**Comment by loopy750** [comment]
I understand this has been closed, (and maybe it's ignorance on my part), but I still can't work out how to get InForm to compile with the latest version 3.8.0. Is it now working and requires me to work it out on my end, or is there still more to be done?

**Comment by a740g** [comment]
> I understand this has been closed, (and maybe it's ignorance on my part), but I still can't work out how to get InForm to compile with the latest version 3.8.0. Is it now working and requires me to work it out on my end, or is there still more to be done?

We have an updated version of InForm that works with QB64-PE v3.8.0. See here: https://qb64phoenix.com/forum/showthread.php?tid=1756&pid=16830#pid16830

GitHub link: https://github.com/a740g/InForm-PE

**Comment by loopy750** [comment]
That's excellent, trying it now.

`MessageBox` appears to have been removed?

Also this line is now causing a **"Memory region out of range"** error, which it had never done previously:
`_MEMPUT m, m.OFFSET, btemp$`

Should I continue discussing this on the forum instead?

**Comment by a740g** [comment]
> MessageBox appears to have been removed?

Yes, this has been removed because QB64-PE has native common dialog support. See https://qb64phoenix.com/qb64wiki/index.php/MESSAGEBOX

> Also this line is now causing a "Memory region out of range" error, which it had never done previously:
_MEMPUT m, m.OFFSET, btemp$

Not really sure about this. This has nothing to do with InFrom.

> Should I continue discussing this on the forum instead?

Yes, that is a good idea. Other users can also chime in if they have quick solutions.

**Comment by loopy750** [comment]
> Not really sure about this. This has nothing to do with InFrom.

Sorry, that's correct, I didn't make that clear. It's using code from a program called `BIN2INCLUDE` which converts an image to a variable. I might have to investigate this issue separately to see if something has changed between 3.6.0 and 3.8.0.

**Comment by loopy750** [comment]
Reported new issue on my finding https://github.com/QB64-Phoenix-Edition/QB64pe/issues/350
