### ISSUE TITLE
Max number of subs and functions in entire program limited to `1000`

### ISSUE THREAD

**Issue by grymmjack** [QB64-Phoenix-Edition/QB64pe#362]
It would be nice to have the ability to exceed `1000`

I created a simple test here, changing `1000` to `10000` in `qb64pe.bas`:
```vb
933: DIM SHARED sfidlist(10000) AS LONG
934: DIM SHARED sfarglist(10000) AS INTEGER
935: DIM SHARED sfelelist(10000) AS INTEGER
```

And it works.

My code which exceeded the `1000` limit was discovered because it was showing a compiler error with line number `11756`.

The code from `qb64pe.bas` around lines `11756` is this:
https://github.com/QB64-Phoenix-Edition/QB64pe/blob/4c50c8db3cb33c52b218d508583c7ff82571a838/source/qb64pe.bas#L11729-L11765

Thanks @mkilgore for your help in discord. I think just 10x'ing the limit would fix the problem but you mentioned you want to be more frugal as you said:
```
Well typically for these we just redim them to be larger after checking the size, we could do that pretty easily here I think.
```

**Comment by mkilgore** [comment]
I think the redim approach is better long-term, but if it's a bit too messy to implement then raising the limit to 10000 seems fine to me, the increase in memory usage is negligible 🤷 

That said, if we're not doing the `redim` approach then I think I'd like to see a simple error check so that the user gets a better error about reaching the max number of subs/functions (instead of an internal compiler error). But at that point, you could just replace the error message with a `redim` and fix the problem, so perhaps it's not worth it XD...

**Comment by SteveMcNeill** [comment]
I think this needs a couple of things to fix it properly.
Redim and increase the limit by 1000 per increase, but only to a finite hard limit.  The reason for this limit is in case the IDE glitches at some point translating the BAS to C, to prevent an endless loop using up all one's memory and swap file space.
When the hard limit is hit, the IDE needs to toss a more descriptive error message asking the user to report the glitch and share code via discord, github, or the forums with the dev team.  In *MOST* cases, an user isn't going to have 10,000 subs and functions in a program.  (Currently 1000, but the actual limit will be whatever the Redim cap tops out at.)  For most users,if there's a glitch here, it's on our end and not there's, and is something we need to be aware of to address.

**Comment by grymmjack** [comment]
Thanks @a740g for this fix!

**Comment by SteveMcNeill** [comment]
Yeah...  *sniffle*   Thanks for this fix @a740g....   

Nobody ever thanks the amazing steve......  sniffle.... sniffle....  WAAAAAHHHHHHHH!!!!

:D

**Comment by a740g** [comment]
> Yeah... _sniffle_ Thanks for this fix @a740g....
> 
> Nobody ever thanks the amazing steve...... sniffle.... sniffle.... WAAAAAHHHHHHHH!!!!
> 
> :D

Yeah. This was @SteveMcNeill not me @grymmjack. All I did, was link your issue to Steve's PR. 😊

**Comment by grymmjack** [comment]
> Yeah...  *sniffle*   Thanks for this fix @a740g....   
> 
> 
> 
> Nobody ever thanks the amazing steve......  sniffle.... sniffle....  WAAAAAHHHHHHHH!!!!
> 
> 
> 
> :D
> 
> 

Ahhh sorry man!! I thought it was Sam. 

Thank you @SteveMcNeill !!!
