### ISSUE TITLE
$Embed and _Embed 

### ISSUE THREAD

**Issue by SteveMcNeill** [QB64-Phoenix-Edition/QB64pe#383]
As we discussed in the Discord, it'd be nice if we could expand the $MidiSoundFont to become a more generic command which would allow us to embed any file into the EXE, and retrieve it later for use with the "memory" commands.

$EMBED "cour.ttf", "handle1"   <-- embed the font file and assign it to "handle1" as a working label at compile time.
dta$ = _Embed("handle1")     <-- use that label to retrieve the data from that embeded file at run time.

**Comment by a740g** [comment]
Love this idea. However, I would use the DATA keyword rather than introducing a new one. Just a personal preference.

So,
```vb
$DATA "cour.ttf", "handle1"
```
and
```vb
dta$ = _DATA("handle1")
```

**Comment by SteveMcNeill** [comment]
I personally liked the _Embed keyword as you're simply embedding one file's contents into another -- be that sound, image, font, or text data.  Folks are used to DATA requiring READ statements and commas and QBASIC formatting.  I think the different keyword helps differentiate the different behavior between the two utilities.  ;)
