### ISSUE TITLE
_SndRawLen always returns 0 no matter how many seconds of data are left to be played

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#39]
_SndRawLen always returns 0 no matter how many seconds of data are left to be played.

For example, in the code below it always returns 0.
We know that there is enough sound data in the queue because even when the loop is exited, we can still hear the sound playing for a long time.

```VB
Dim h As Long
h = _SndOpenRaw
Do
    _SndRaw Rnd - Rnd, Rnd - Rnd, h
    Locate 1, 1: Print _SndRawLen;
Loop While Len(InKey$) = 0
_SndClose h
```

For _SndRawLen , the [wiki](https://qb64phoenix.com/wiki/www.qb64.org/wiki/SNDRAWLEN.html) says:
```
The _SNDRAWLEN function returns the length, in seconds, of a sound currently queued.
Use _SNDRAWLEN to determine the length of a sound queue during creation and when to stop playing the sound.
Ensure that _SNDRAWLEN is comfortably above 0 (until you've actually finished playing sound).
If you are getting occasional random clicks, this generally means that _SNDRAWLEN has dropped to 0.
```

Clearly, this is not the way this is working at the moment.

Note: Please turn down your volume when running the above snippet. It's not pretty. 🙂

### Update:
_SndRawLen works when _SndRaw is used without a handle, as shown below.

```VB
Do
    _SndRaw Rnd - Rnd, Rnd - Rnd
    Locate 1, 1: Print _SndRawLen;
Loop While Len(InKey$) = 0
```

Well, this was unexpected. A better way for _SndRawLen to work would be to return the time left for "handle-less" streams and streams with handles when specified.

`length# = _SndRawLen [pipeHandle&]`

**Comment by a740g** [comment]
@mkilgore I updated the issue.

**Comment by a740g** [comment]
We can probably close this as resolved now that the wiki has correct and updated docs for both _SndRawDone and _SndRawLen per #91.

**Comment by mkilgore** [comment]
Right, I gotcha, the underlying issue then was the mix of using a handle for `_SndRaw` but not using the handle with `_SndRawLen`, correct? That makes enough sense, it would probably be more straight forward if there was no handle-less option for the `_SndRaw` stuff, but that definitely can't be changed now 🤷‍♂️

**Comment by a740g** [comment]
Correct. The issue was with the wiki to being with. @RhoSigma-QB64 fixed the wiki. Now we should be good.
