### ISSUE TITLE
Console on Windows

### ISSUE THREAD

**Issue by TheXadGaming** [QB64-Phoenix-Edition/QB64pe#396]
When I open QB64PE on in Windows a console opens with it's, and both windows are dependent on each other, if one closes the other does. I've only seen this bug in Windows 11, tested on 10 and 7 and it didn't happen.

To produce just open QB64PE in Windows 11.

It should open the console for second or in the background and close again leaving just the IDE.

Info:
 - OS: Windows 11 Home
 - Browser (Not necessary but I use Chrome)
 - Version Most Versions of Windows 11.

**Comment by spriggsyspriggs** [comment]
Can you confirm if this is the regular CMD console window _or_ if this is the Windows Terminal. Windows Terminal behaves differently from CMD and is not caused by a bug in QB64pe.

**Comment by TheXadGaming** [comment]
Here's a photo:
![image](https://github.com/QB64-Phoenix-Edition/QB64pe/assets/108760829/403fb42a-91c0-468d-9b8b-d45edd79f9a6)

**Comment by spriggsyspriggs** [comment]
Right. This is the Windows Terminal, which behaves differently from CMD. You would need to change your default terminal by going into the settings of Windows Terminal and selecting CMD.

**Comment by TheXadGaming** [comment]
Thank you, I fixed the issue.

**Comment by spriggsyspriggs** [comment]
Great! Glad to hear it.
