### ISSUE TITLE
I need help with beep, sound, and play

### ISSUE THREAD

**Issue by Lightwave234** [QB64-Phoenix-Edition/QB64pe#411]
**Describe the bug**
I keep getting a segmentation fault every time I try using play, beep, or sound, and I also don't hear anything

**To Reproduce**
1. clone the repository to my Linux subsystem
2. follow all the steps to setting up the application
3. type "play/beep/sound" into a new file, then run

**Expected behavior**
A sound should come from the app, but nothing happens and when I run, I see the text "Segmentation fault"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux subsystem for Windows
 - Version: Ubuntu 22.04

**Comment by a740g** [comment]
I just tried `BEEP`, `PLAY` and `SOUND` examples from the wiki on Ubuntu 22.04 (WLS) and everything worked just fine.
I am using QB64-PE v3.9.1 from https://github.com/QB64-Phoenix-Edition/QB64pe/releases/latest

Which version of QB64-PE are you using?

**Comment by SteveMcNeill** [comment]
As this is now nearly two month old, with no update from the original poster and no other reports of the same behavior, I'm going to close this issue for now.
