### ISSUE TITLE
IDE option to always recompile current program even if the editor does not detect changes

### ISSUE THREAD

**Issue by RetroNick2020** [QB64-Phoenix-Edition/QB64pe#433]
**Is your feature request related to a problem? Please describe.**
when I modify an $INCLUDE file or $EMBED file the IDE does not know external files were changed

**Describe the solution you'd like**
An option in the IDE to always force a new compile even if the IDE does not detect changes

**Describe alternatives you've considered**
I am constantly inserting a space in an empty line of the program to force the IDE/Compiler to compile again

**Additional context**

**Comment by RhoSigma-QB64** [comment]
Hi @RetroNick2020 ,

you're Issue was addressed in pull request #442, however we waive to another menu option and rather made the IDE smart enough to detect changes to those files automatically and correctly rebuild the program if needed. This includes not only $EMBED files, but also $EXEICON, $MIDISOUNDFONT and even regular $INCLUDE files, so no more worries, just edit your external files press F5 and the IDE will correctly recompile if needed.
