### ISSUE TITLE
`$FULLSCREEN:DISABLED` AND `$FULLSCREEN:ENABLED`

### ISSUE THREAD

**Issue by grymmjack** [QB64-Phoenix-Edition/QB64pe#451]
I would like to be able to disable fullscreen, `ALT+ENTER`, etc.

It would be great if we simply had two more special commands like:
- `$FULLSCREEN:DISABLED` to disable the ability to use `ALT+ENTER` to toggle full screen as user.
- `$FULLSCREEN:ENABLED` to enable the ability to use `ALT+ENTER` to toggle full screen as user. (DEFAULT)

It seems we cannot block, ignore, or prevent this functionality in QB64.

This would be especially useful in InFormPE programs.

Thank you!

**Comment by FellippeHeitor** [comment]
There's ```_ALLOWFULLSCREEEN```

**Comment by grymmjack** [comment]
Thank you @FellippeHeitor ! Closing!
