### ISSUE TITLE
MOUSEMOVEMENTX/Y does not work properly on MacOS

### ISSUE THREAD

**Issue by TeddyKlugs** [QB64-Phoenix-Edition/QB64pe#465]
The commands stop reporting position changes at the edges of the desktop instead of continuing infinitely. On my machine the extremes of the X movements are -50 to desktopwidth - 50. I haven't played around with Y movements.

**Comment by a740g** [comment]
@TeddyKlugs Thank you.

Adding forum link where this was discussed and reported.
https://qb64phoenix.com/forum/showthread.php?tid=2445

**Comment by SteveMcNeill** [comment]
Also want to add a note that _MouseMove is glitchy on Mac.  (At least IMHO, it is.)  Any time it's called, glut locks out all keyboard and mouse input for 250ms, for some odd reason.  This should also be looked into at the same time the _MouseMomentX/Y stuff is examined.  ;)
