### ISSUE TITLE
IDE "Internal error" fault when editing

### ISSUE THREAD

**Issue by electric-socket** [QB64-Phoenix-Edition/QB64pe#471]
**Describe the bug**
While writing and correcting text in the QB64pe IDE it repeatedly faults, often without allowing further text editing (but it will still save) I've gotten in  the habit of excessively saving, like on every line, in fear the IDE will fault.

**To Reproduce**
1. Load a program
2. Do some editing
3. IDE faults with "Internal IDE error module ide_methods on line 1333" or "Internal IDE error module ide_methods on line 1250" possily other lines. Fault occurs multiple times (>5) a day at random times. One time it faulted on line 1250 and completely locked up, nothing works, no response and can't close by clicking the kill box. I had to use task manager to "terminate with extreme prejudice."

**Expected behavior**
Nothing; the IDE should just silently accept text changes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win  10 pro
 - Version [e.g. 22]  Phoenix Edition 3.12.0

**Comment by mkilgore** [comment]
Try deleting your `internal/temp/undo2.bin` file, I can't say what exactly happened to it but that's the likely cause of the issue.

**Comment by flukiluke** [comment]
Closing as there is nothing to do here unless further information comes to light
