### ISSUE TITLE
Add option to replicate QBasic 1.1 quirk: pause on SOUND

### ISSUE THREAD

**Issue by Poikilos** [QB64-Phoenix-Edition/QB64pe#494]
**Is your feature request related to a problem? Please describe.**
My action games used inaudible sounds (SOUND command) for timing, but QB64 doesn't pause on them so they run at ultra-fast speed. 

**Describe the solution you'd like**
As a compiler option, replicate the quirk, so that the program execution pauses during the SOUND.

**Describe alternatives you've considered**
The source code of the game would have to be changed. Reproducing the quirk seems better to allow old code to run as expected.

**Additional context**
I programmed the games this way since trying to count the number of CPU cycles per second got too many once processors got well beyond 100 MHz. The SOUND command was the most accurate "low-level timer" I could figure out at the time.
- I'm not sure what other versions of BASIC have this quirk. Maybe someone could offer input.
- QBasic 1.1 code that demonstrates the issue is at https://github.com/Hierosoft/qjak (games are too fast to play)

**Comment by grymmjack** [comment]
Hi @Poikilos first thanks!

Second, if you are expecting 100% compatibility with QBasic 1.1 in QB64PE, you might want to adjust your expectations a little bit. It's compatible as a goal for sure, but it's not 100% 1:1 compatible, and I don't know if it ever will be.

That said, for speed issues and timing, there are a few great things you could do to modify your older code to work as you want in QB64PE specifically:

[_LIMIT](https://qb64phoenix.com/qb64wiki/index.php/LIMIT) and [_DELAY](https://qb64phoenix.com/qb64wiki/index.php/DELAY) - both of these will help you time your code.

There are some caveats, but _LIMIT in the loops is where I have had success in slowing things down.

Also, there is a great forum article on delta time here:
https://qb64phoenix.com/forum/showthread.php?tid=2243&highlight=delta

It might be that [delta time](https://qb64phoenix.com/forum/showthread.php?tid=2243&highlight=delta) is what you are after!

Good luck.

**Comment by Poikilos** [comment]
Thanks for the help. Usually, the "PLAY MB" statement causes PLAY and SOUND statements to run in the background, but foreground ("PLAY MF", interrupting the process) is the default:
- https://www.pcjs.org/documents/books/mspl13/basic/qblang/ (search for "MB" or "subsequent note" to find the documentation section)
- http://www.antonis.de/qbebooks/gwbasman/index.html

**Comment by a740g** [comment]
> Thanks for the help. Usually, the "PLAY MB" statement causes PLAY and SOUND statements to run in the background, but foreground ("PLAY MF", interrupting the process) is the default:
> 
> * https://www.pcjs.org/documents/books/mspl13/basic/qblang/ (search for "MB" or "subsequent note" to find the documentation section)
> * http://www.antonis.de/qbebooks/gwbasman/index.html

Actually, QB64-PE does pause execution by default when `SOUND` and `PLAY` are called. `PLAY "mb"` enables background playback. If you are using SOUND for timing, it may not be super perfect, but it should work. TIMER related code *will* keep running while QB64-PE waits for the sound to finish playing.

QB64-PE had this for some time now.

Which version of QB64 or QB64-PE are you using? Just curious.

**Comment by Poikilos** [comment]
Ok, so it turned out I was using the old one, QB64 2.0.2 stable (git 4d85302). The behavior, queued sounds interrupting later execution but not pausing when used, is fixed.

I do not have the issue in Phoenix Edition 3.13.1. Thanks!
