### ISSUE TITLE
[WIKI][DOCS] Add Downloadable Documentation support for entire Wiki

### ISSUE THREAD

**Issue by TheRealHamtaro126** [QB64-Phoenix-Edition/QB64pe#509]
Is your feature request related to a problem? YES

Please describe:
This is actually a problem relating to the options seeing and viewing the whole Wiki as is.
There is no PDF or such download options for viewing...

Describe the solution you'd like:
Add a "Save/Download Wiki (for Offline Reading)", but only for use as a reference point in
programming QB64

Describe alternatives you've considered:
Please, no torrents... I do mainly like manuals in entire PDF or maybe TXTs,
I'd also like to point to an open source alternative to Office (such as LibreOffice) if doing Rich Text docs instead of PDF, (Also, Microsoft Office stinks)...

**Comment by RhoSigma-QB64** [comment]
All keyword wiki pages are already available offline in the IDE help system. More pages are downloaded on demand as soon a respective link is selected. See the HELP menu in the upper right corner of the IDE.

**Comment by RhoSigma-QB64** [comment]
Wiki main page got a new link to the forum thread where members share their offline versions of the Wiki in various formats. More is not planned on this issue.
