### ISSUE TITLE
Change about screen to show Phoenix Edition

### ISSUE THREAD

**Issue by jakebullet70** [QB64-Phoenix-Edition/QB64pe#71]
Change about screen to show Phoenix Edition.

**Comment by mkilgore** [comment]
I believe we already did this, does it not look like this for you? How did your get your copy of QB64PE?

![image](https://user-images.githubusercontent.com/3310024/169031813-526ee14b-0f38-47bd-bf1a-e00b1781b807.png)

**Comment by jakebullet70** [comment]
no, grabbed it today from here.

![image](https://user-images.githubusercontent.com/14124210/169052608-dce0fd1b-180a-4320-9fa2-2a506dfd4edc.png)
![image](https://user-images.githubusercontent.com/14124210/169055204-ae8fcd5a-7bc6-4044-9191-4077596e7a69.png)

**Comment by mkilgore** [comment]
I see, you grabbed this one: https://github.com/QB64-Phoenix-Edition/QB64pe/releases/tag/v1.0alpha

The newest version is actually the `0.6.0`, that will be more obvious once we make our first major release. I think I'll see if we can just hide that release as it was done before we started actually versioning it.
