### ISSUE TITLE
CURL not found in Windows

### ISSUE THREAD

**Issue by jakebullet70** [QB64-Phoenix-Edition/QB64pe#76]
Windows version.
Help menu.
Update All Pages.
Looks for 'curl' and fails.

**Comment by RhoSigma-QB64** [comment]
1. Get **curl** here (https://curl.se/windows/), download according to your system, or simply the 32 bit version, if you're not sure.
2. Open the downloaded zip in explorer, navigate into the **bin** folder
3. Copy **curl.exe** and **curl-ca-bundle.crt** and paste it into C:\Windows
4. If you have no rights on C:\Windows, then simply paste it into your qb64 folder (where qb64.exe is in)

**Comment by jakebullet70** [comment]
OK, Put them in the QB64 folder and all is good.
Thinking we need to add to the install or download when needed?

**Comment by mkilgore** [comment]
The messy part is that some versions of Windows do include proper `curl`, while some other ones do not. Also, simply downloading `curl.exe` and `curl-ca-bundle.crt` is not really ideal because as Rho encountered the cert bundle can go out of date. We might consider adding `curl.exe` as part of the install temporarily but I think we should look to remove our usage of it in the future (Which was part of the idea behind #46).

**Comment by jakebullet70** [comment]
I think doing #46 is your long term answer. Short term...  Maybe just picking up the return code from the  SHELL too curl and putting a message on the screen. That would at least get the user pointed in the right direction for the fix.

**Comment by mkilgore** [comment]
Do you mean pop-up a more descriptive message than the one we currently do? Or did you not see a message at all?

**Comment by jakebullet70** [comment]
Here is the message. 

![image](https://user-images.githubusercontent.com/14124210/169831843-4700185a-f68a-4ec9-a530-8a5a63120a26.png)

Yeah, more descriptive. Thinking like point the user to the web and tell them to download curl. If I had seen a message like that would not of posted a bug.

**Comment by jakebullet70** [comment]
Also, if you do the 'Update all pages' it gets stuck in a loop, You keep getting the 'Cannot find curl' message over and over. Should drop out of the loop if it cannot find curl.

**Comment by mkilgore** [comment]
Thanks for the clarification, that seems reasonable to me 😄 And also good point about the 'Update all pages' getting stuck, that's not great. I think we can probably handle both issues with this card.
