### ISSUE TITLE
Populate ./internal/help during the CI build

### ISSUE THREAD

**Issue by mkilgore** [QB64-Phoenix-Edition/QB64pe#77]
Currently we keep a copy of the help files in `./internal/help` so that they can be used when QB64 is downloaded without needing to download a copy. Keeping the copy in `./internal/help` in this repository is a bit messy though, so we should look into trying to download a fresh copy of `./internal/help` during the CI build - so that the repo doesn't have to contain a copy, but released versions of QB64 will has a fresh copy of whatever was present when it was released.

**Comment by RhoSigma-QB64** [comment]
Fixed by #136 .
