### ISSUE TITLE
Are the parameters for _CopyImage really optional?

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#79]
The QBPE [wiki](https://qb64phoenix.com/qb64wiki/index.php/COPYIMAGE) says:
`If imageHandle& parameter is omitted or zero is designated, the current software destination screen or image is copied`

However, this is not how this works in the IDE like shown in the line below. The IDE complains about `Incorrect number of arguments`.

```tmp& = _CopyImage```

So, this should either be corrected in the wiki or in code.

**Comment by RhoSigma-QB64** [comment]
Under investigation...

**Comment by RhoSigma-QB64** [comment]
As it appears, the functionality was already changed a decade ago.
I've updated the Wiki page to reflect the changes, thanks for reporting.
