### ISSUE TITLE
 _SndRawDone accepts a QB64 sound pipe handle

### ISSUE THREAD

**Issue by a740g** [QB64-Phoenix-Edition/QB64pe#91]
I discovered this purely by accident while working on my QB64 MOD Player. 

_SndRawDone accepts a QB64 sound pipe handle like:

`_SndRawDone pipeHandle&`

However, the QBPE [wiki](https://qb64phoenix.com/qb64wiki/index.php/SNDRAWDONE) says otherwise:
```
Syntax
_SNDRAWDONE
```

I guess we need to update the wiki.

**Comment by RhoSigma-QB64** [comment]
Updated the Wiki pages for `_SNDRAWLEN` and `_SNDRAWDONE`.
Thanks for reporting.
