### ISSUE TITLE
_CONNECTIONADDRESS$() for _OPENHOST() handles does not work

### ISSUE THREAD

**Issue by mkilgore** [QB64-Phoenix-Edition/QB64pe#92]
_CONNECTIONADDRESS$() is based on calling the code in [`myip.cpp`](https://github.com/QB64-Phoenix-Edition/QB64pe/blob/main/internal/c/myip.cpp), but unfortunately it works by making a request to `www.qb64.org/ip.php` to attempt and resolve the user's public IP. Obviously the url does not work anymore, so presumably this function is broken.

**Comment by mkilgore** [comment]
@RhoSigma-QB64 kindly set it up to be hosted on the new `qb64phoenix.com`: https://qb64phoenix.com/qb64_files/ip.php

I think there's probably some conversation to be had over what should happen to this functionality long term, but for now the URL can be swapped out easily enough.

**Comment by mkilgore** [comment]
https://api.ipify.org/ was suggested by @SpriggsySpriggs. Considering the need to have the link be stable (since it is embedded into QB64 programs using this functionality) it seems like a reasonable alternative to use.

**Comment by SpriggsySpriggs** [comment]
It also allows HTTP connections so we'd be able to do a regular HTTP GET request on port 80

**Comment by RhoSigma-QB64** [comment]
The **Phoenix rebranding** pull request #136 does finally implement the changes to use the new url https://qb64phoenix.com/qb64_files/ip.php
